{{ $serv_id := "conductor-server" }}
{{ $serv_uidgid := .Values.env.CONDUCTOR_SERVER_UID_GID }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge (dict "image_id" "fms-conductor-server") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          env:
          - name: "DB_URL"
            value: "conductor-postgresql:5432/conductor"
          - name: "DB_USERNAME"
            value: "postgres"
          - name: "DB_PASSWORD_FILE"
            value: "/run/secrets/conductor_db_pwd"
          - name: "DB_MAX_POOLSIZE"
            value: "10"
          - name: "DB_MIN_POOLSIZE"
            value: "2"
          - name: "INDEXING_ENABLED"
            value: "true"
          - name: "ELASTICSEARCH_URL"
            value: "http://conductor-elasticsearch:9200"
          - name: "CONFIG_FILE"
            value: "config-local.properties"
          - name: "SYSTEM_TASK_WORKER_THREAD_COUNT"
            value: "100"
          - name: "SYSTEM_TASK_WORKER_POLL_INTERVAL"
            value: "100"
          - name: "LOG4J_FORMAT_MSG_NO_LOOKUPS"
            value: "true"
          - name: "ADDITIONAL_PARAMETERS"
            value: ""
          - name: "JAVA_OPTS"
            value: "-Xms1024m -Xmx2042m"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 8
            # Allowed startup time
            failureThreshold: 66
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 8
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
          - name: conductor-db-pwd
            mountPath: /run/secrets/conductor_db_pwd
            subPath: secret
            readOnly: true
          resources:
            limits:
              memory: "3072M"
            requests:
              memory: "307.2M"
      volumes:
      - name: conductor-db-pwd
        secret:
          secretName: {{.Values.env.CONDUCTOR_DB_PASSWORD_SECRET}}
          defaultMode: 0440
