{{ $serv_id := "service-authorization-proxy" }}
{{ $serv_uidgid := .Values.env.SERVICE_AUTHORIZATION_PROXY_UID_GID }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge (dict "image_id" "fms-service-authorization-proxy") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          env:
          - name: "KEYCLOAK_DNS"
            value: "{{.Values.env.KEYCLOAK_DNS}}"
          - name: "IAM_PROXY"
            value: "http://keycloak-proxy:10000"
          - name: "IAM_SERVICE_AUTHORIZATION_PROXY_CLIENT_ID"
            value: "{{.Values.env.IAM_SERVICE_AUTHORIZATION_PROXY_CLIENT_ID}}"
          - name: "KEYCLOAK_SERVICE_AUTHORIZATION_PROXY_SECRET_FILE"
            value: "/run/secrets/iam_service_authorization_proxy_client_secret"
          volumeMounts:
          - mountPath: /run/secrets/iam_service_authorization_proxy_client_secret
            name: iam-service-authorization-proxy-client-secret
            subPath: secret
            readOnly: true
          resources:
            limits:
              memory: "2048M"
            requests:
              memory: "204.8M"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8085
            timeoutSeconds: 8
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8085
            initialDelaySeconds: 2
            timeoutSeconds: 8
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
      - name: iam-service-authorization-proxy-client-secret
        secret:
          secretName: {{.Values.env.IAM_SERVICE_AUTHORIZATION_PROXY_CLIENT_SECRET}}