{{ $serv_id := "measurement-files" }}
{{ $serv_uidgid := .Values.env.MEASUREMENT_FILE_UID }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  serviceName: {{ include "fms.fullname" . }}-{{$serv_id}}
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge (dict "image_id" "fms-measurement-files") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          env:
          - name: MONGO_HOST
            value: "measurement-data-db"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "{{ .Values.env.MONGO_USERNAME_MEASURE }}"
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: "/run/secrets/measure_db_pwd"
          - name: MONGO_DATABASE
            value: "optical-services"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: USE_SSL
            value: "false"
          - name: USE_KEYCLOAK
            value: "false"
          - name: SERVICE_HOST_NAME
            value: "{{ .Values.env.DATA_DNS }}"
          volumeMounts:
          - name: data
            mountPath: /var/www/ClientsData
          - name: measure-db-pwd
            mountPath: /run/secrets/measure_db_pwd
            subPath: secret
            readOnly: true
          resources:
            limits:
              memory: "2048M"
            requests:
              memory: "204.8M"
      volumes:
      - name: measure-db-pwd
        secret:
          secretName: {{.Values.env.MONGO_PASSWORD_MEASURE_SECRET}}
          defaultMode: 0440
  volumeClaimTemplates:
  - metadata:
      name: data
    {{- include "fms.volumeclaim.data" (merge (dict "id" $serv_id) $) | nindent 4 }}