{{ $serv_id := "conductor-postgresql" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP