{{ $serv_id := "rtu-broker" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: activemq
      port: 61617
      targetPort: 61617
      protocol: TCP