{{ $serv_id := "topology-postgresql-replica" }}
{{- if eq .Values.env.REPLICATION_ENABLED "true" }}
{{ include "fms.volume.replication-data" (merge (dict "id" $serv_id "path" .Values.env.TOPOLOGY_DATA) $)}}
{{- end }}
