{{ $serv_id := "rtu-log-collector" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP