{{ $serv_id := "measurement-files" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: http
      port: 9080
      targetPort: 9080
      protocol: TCP