{{ $serv_id := "measurement-data-db" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP