{{ $serv_id := "rtu-log-collector" }}
{{ $serv_uidgid := .Values.env.RTU_LOG_COLLECTOR_UID_GID }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge ( dict "image_id"  "fms-rtu-log-collector" ) $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          env:
          - name: RTU_LOG_COLLECTOR_LEVEL
            value: "info"
          - name: RTU_LOG_COLLECTOR_FILE
            value: "fluent-bit.log"
          - name: RTU_LOG_COLLECTOR_HTTP_PORT
            value: "8888"
          - name: RTU_LOG_COLLECTOR_HEALTH_PORT
            value: "2020"
          - name: AUDITLOGS_CONF_AGE
            value: "maxage {{.Values.env.RTU_AUDIT_LOG_EXPIRATION_PERIOD }}"
          volumeMounts:
          - name: logs
            mountPath: /output
          resources:
            limits:
              memory: "1024M"
            requests:
              memory: "102.4M"
          livenessProbe:
            httpGet:
              path: /
              port: 2020
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 2020
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
      volumes:
      - name: logs
        {{- include "fms.pod-volume.log" (merge (dict "id" $serv_id "path" .Values.env.RTU_LOG_COLLECTOR) $) | nindent 8 }}
