{{ $serv_id := "conductor-elasticsearch" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      protocol: TCP