{{ $serv_id := "victoria-metrics" }}
{{ $serv_uidgid := .Values.env.VICTORIA_METRICS_UID_GID }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  serviceName: {{ include "fms.fullname" . }}-{{$serv_id}}
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          image: "victoriametrics/victoria-metrics:v1.77.2"
          imagePullPolicy: IfNotPresent
          args:
          - '--retentionPeriod={{.Values.env.VICTORIA_METRICS_RETENTION_PERIOD_MONTHS}}'
          resources:
            limits:
              memory: "{{.Values.env.MEMORY_LIMIT_VICTORIA_METRICS_MO}}M"
            requests:
              memory: "{{div .Values.env.MEMORY_LIMIT_VICTORIA_METRICS_MO 3 }}M"
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 8428
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 8428
            initialDelaySeconds: 240
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: victoria-metrics
            mountPath: /victoria-metrics-data
      volumes:
      - name: victoria-metrics
        hostPath:
          path: {{ .Values.env.ROOT_PATH }}{{ .Values.env.PERSISTENT_DATA_DIR }}{{ .Values.env.VICTORIA_METRICS_DATA }}
  volumeClaimTemplates:
  - metadata:
      name: data
    {{- include "fms.volumeclaim.data" (merge (dict "id" $serv_id) $) | nindent 4 }}
