{{ $serv_id := "alarming-metrics" }}
{{ $serv_uidgid := .Values.env.ALARMING_METRICS_UID_GID }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  serviceName: {{ include "fms.fullname" . }}-{{$serv_id}}
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge (dict "image_id" "optical-trending") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          args:
          - "--alertmanager.notification-queue-capacity=100000"
          - "--storage.tsdb.retention.time=30d"
          volumeMounts:
          - name: data
            mountPath: /prometheus
          - name: config
            mountPath: /etc/prometheus.custom
          resources:
            limits:
              memory: "{{.Values.env.MEMORY_LIMIT_ALARMINGMETRICS_MO}}M"
            requests:
              memory: "242M"
          livenessProbe:
            exec:
              command:
              - /bin/wget
              - -q
              - -Y off
              - http://localhost:9090/-/healthy  
              - -O
              - /dev/null 
            initialDelaySeconds: 90
            timeoutSeconds: 8
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3      
          readinessProbe:
            exec:
              command:
              - /bin/wget
              - -q
              - -Y off
              - http://localhost:9090/-/healthy  
              - -O
              - /dev/null
            timeoutSeconds: 8
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
      volumes:
      - name: config
        {{- include "fms.pod-volume.config" (merge (dict "id" $serv_id ) $) | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    {{- include "fms.volumeclaim.data" (merge (dict "id" $serv_id) $) | nindent 4 }}