{{ $serv_id := "conductor-elasticsearch-cerebro" }}
{{ $serv_uidgid := .Values.env.CONDUCTOR_CEREBRO_UID_GID }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  serviceName: {{ include "fms.fullname" . }}-{{$serv_id}}
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: {{$serv_id}}
          {{ include "fms.docker-image" (merge (dict "image_id" "fms-elasticsearch-cerebro") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: 
          - "-c"
          - |
              mkdir -p /opt/cerebro/data
              exec /opt/cerebro/bin/cerebro -Ddata.path=/opt/cerebro/data/cerebro.db
          env:
          - name: CEREBRO_PORT
            value: "8080"
          volumeMounts:
          - name: data
            mountPath: /opt/cerebro/data
          - name: cerebro-logs
            mountPath: /opt/cerebro/logs
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 8
            # Allowed startup time
            failureThreshold: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 8
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              memory: "1024M"
            requests:
              memory: "102.4M"
      volumes:
      - name: cerebro-logs
        hostPath:
          path: {{ .Values.env.ROOT_PATH }}{{ .Values.env.LOG_DIR }}{{ .Values.env.CONDUCTOR_CEREBRO }}
  volumeClaimTemplates:
  - metadata:
      name: data
    {{- include "fms.volumeclaim.data" (merge (dict "id" $serv_id) $) | nindent 4 }}
