{{ $serv_id := "rtu-configuration-validator" }}
{{ $serv_uidgid := .Values.env.RTU_CONFIGURATION_VALIDATOR_UID_GID }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fms.fullname" . }}-{{$serv_id}}
  labels:
    {{- include "fms.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{$serv_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{$serv_id}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "fms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: {{$serv_id}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fms.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ (split ":" $serv_uidgid)._0 }}
        runAsGroup: {{ (split ":" $serv_uidgid)._1 }}
        fsGroup: {{ (split ":" $serv_uidgid)._1 }}
      nodeSelector:
        role: "primary"
      containers:
        - name: main
          {{ include "fms.docker-image" (merge (dict "image_id" "fms-rtu-configuration-validator") $ ) | nindent 10 }}
          imagePullPolicy: IfNotPresent
          env:
          - name: USE_KEYCLOAK
            value: "false"
          # case sensitive and one of these values {fatal, error, warn, info, debug, trace}
          - name: TEST_CONFIGURATION_LOG_LEVEL
            value: "warn"
          resources:
            limits:
              memory: "2048M"
            requests:
              memory: "204.8M"
          livenessProbe:
            exec:
              command:
              - curl
              - -f
              - http://localhost:8080/healthcheck
            initialDelaySeconds: 240
            timeoutSeconds: 8
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3      
          readinessProbe:
            exec:
              command:
              - curl 
              - -f
              - http://localhost:8080/healthcheck
            initialDelaySeconds: 30
            timeoutSeconds: 8
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3