{{ $serv_id := "topology-api" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
