{{ $serv_id := "measurement-data" }}
apiVersion: v1
kind: Service
metadata:
  name: measurement
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
