{{ $serv_id := "conductor-elasticsearch-cerebro" }}
apiVersion: v1
kind: Service
metadata:
  name: {{$serv_id}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/service: {{$serv_id}}
  ports:
    - name: elasticsearch-cerebro
      port: 8080
      targetPort: 8080
      protocol: TCP